#!/bin/bash
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-destkop-portal-gtk
killall xdg-desktop-portal-gnome
killall xdg-destkop-portal-wlr
killall xdg-destkop-portal
logger 'killed them opps'
sleep 1
/usr/libexec/xdg-desktop-portal-gtk &
logger 'them gtk portal started yo'
sleep 1
/usr/libexec/xdg-desktop-portal-hyprland &
logger 'that hyprportal is uppppp'
sleep 2
/usr/libexec/xdg-desktop-portal &
logger 'the portal hood is complete'
